### ISSUE TITLE
Project Discussion

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/Trip-Management-System#5]
# Project Discussion
@OutdatedGuy @Pratham1402 If you have any suggestions doubts or anything else then use this issue as a discussion window
Before Commenting here please go through [Project.md](https://github.com/malivinayak/Taxi-Management-System/blob/dev/Project.md) File

**Comment by OutdatedGuy** [comment]
Great @malivinayak, however you can turn on discussion tab from settings and create a separate discussion specific post there.

Try it out if you don't know.

**Comment by OutdatedGuy** [comment]
Great structure of [Project.md](https://github.com/malivinayak/Taxi-Management-System/blob/c37165978dbea3e68f12066c421c4b1b72c1e069/Project.md) file 👍🏼

**Comment by malivinayak** [comment]
@OutdatedGuy Thank You for letting me know about discussion tab.
When I started this issue I am thinking about something like discussion tab. But I was unaware about it till now.
Closing this issue as #6 #7 #8
