### ISSUE TITLE
Create admin dashboard to query database

### ISSUE THREAD

**Issue by OutdatedGuy** [malivinayak/Trip-Management-System#52]
### User Query
**API Route - "/api/query/user"**

<details>
<summary> Required Fields </summary>

- [x] 1. fname
- [x] 2. mname
- [x] 3. lname
- [x] 4. gender
- [x] 5. ageR1
- [x] 6. ageR2
- [x] 7. area
- [x] 8. city
- [x] 9. state
- [x] 10. pincode
- [x] 11. birthDateR1
- [x] 12. birthDateR2
</details>

<hr>

### Driver Query
**API Route - "/api/query/driver"**

<details>
<summary> Required Fields </summary>

- [x] 1. fname    
- [x] 2. mname
- [x] 3. lname
- [x] 4. gender
- [x] 5. ageR1 - minimum age
- [x] 6. ageR2 - maximum age
- [x] 7. area
- [x] 8. city
- [x] 9. state
- [x] 10. pincode
- [x] 11. earningR1 - minimum earning
- [x] 12. earningR2 - maximum earning
- [x] 13. expiryDateR1 - minimum license expiry date
- [x] 14. expiryDateR2 - maximum license expiry date
- [x] 15. ratingR1
- [x] 16. ratingR2 
- [x] 17. birthDateR1
- [x] 18. birthDateR2
</details>

<hr>

### Trip Query
**API Route - "/api/query/trip"**

<details>
<summary> Required Fields </summary>

- [x] 1. place1 - Start Place
- [x] 2. place2 - End Place
- [x] 3. dateTime1 - Start Date, Time
- [x] 4. dateTime2 - End Time Date
- [x] 5. fareR1 - minimum trip fare
- [x] 6. fareR2 - maximum trip fare
- [x] 7. isAC - trip is ac or non-ac
- [x] 8. driverID - Driver ID / username of driver
- [x] 9. userID - User ID / username of user
</details>

<hr>

### custom query
**API Route - "/api/query/custom"**
- [x] 1. customQuery - direct query in string format without semicolon (if semicolon present then remove it)

<hr>

**Note : ** Still working on trip query {Fields for trip query may or may not be change}

**Comment by OutdatedGuy** [comment]
@malivinayak, please create checkboxes to note which query fields to create in admin dashboard

**Comment by malivinayak** [comment]
@OutdatedGuy updated the fields as requested

**Comment by OutdatedGuy** [comment]
@malivinayak, no birthdate range for user and driver?

**Comment by malivinayak** [comment]
@OutdatedGuy No need as we are applying filter based on age

**Comment by OutdatedGuy** [comment]
> @OutdatedGuy No need as we are applying filter based on age

But it's more customizable with birthDate as we can even query month and day specific

**Comment by malivinayak** [comment]
I have intentionally but age only as age is not directly stored in database
It is calculated by procedure created in database based on current system date time and birth date
This is one of the utilization of advance database feature

**Comment by malivinayak** [comment]
> But it's more customizable with birthdate as we can even query month and day specific

@OutdatedGuy 
In this case we can go for both DoB as well as age too
As we have to utilize advance DB concepts

**Comment by malivinayak** [comment]
> I have intentionally but age only as age is not directly stored in database It is calculated by procedure created in database based on current system date time and birth date This is one of the utilization of advance database feature

I think this is enough

**Comment by OutdatedGuy** [comment]
> > I have intentionally but age only as age is not directly stored in database It is calculated by procedure created in database based on current system date time and birth date This is one of the utilization of advance database feature
> 
> I think this is enough

Ok but how can I check all the users born in September 2001 without `birthDate` range

**Comment by malivinayak** [comment]
No you can't

lets go for both age as well as DOB

What do you say

**Comment by OutdatedGuy** [comment]
Also append API route name/path before mentioning fields for it. So I can set where to fetch data from.

**Comment by OutdatedGuy** [comment]
@malivinayak, do we have to implement custom queries or not? If yes, tell it's API path and what to send.

**Comment by malivinayak** [comment]
> do we have to implement custom queries or not? If yes, tell it's API path and what to send.

@OutdatedGuy updated the description

**Comment by OutdatedGuy** [comment]
> * 1. customQuery - direct query in string format without semicolon (if semicolon present then remove it)

@malivinayak, removing semicolon has to be handle in backend.
