### ISSUE TITLE
Queried Data remain there after switching from user to driver or any other tab

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/Trip-Management-System#59]
![image](https://user-images.githubusercontent.com/66154908/203192458-208fab50-6f64-4ffb-b5d9-0da3e6550871.png)

I get this data in driver tab
and after switching to user/trip query tab this data must be automatically clear as now we are in user/trip tab

**Comment by OutdatedGuy** [comment]
It's intentionally done so that data won't be lost if tab switched by accident

**Comment by malivinayak** [comment]
> It's intentionally done so that data won't be lost if tab switched by accident

@OutdatedGuy 😂
