### ISSUE TITLE
Create CBS API routes

### ISSUE THREAD

**Issue by OutdatedGuy** [malivinayak/Trip-Management-System#67]
All CBS related routes should be made under `/api/cbs`.

Current required routes:

1. [x] - `/api/cbs/get-balance/:role` to get current balance in wallet
2. [x] - `/api/cbs/add-money` for users to add money to wallet

More routes:

1. [x] - `/api/cbs/withdraw-money` for driver/employees to remove money from wallet

**Comment by malivinayak** [comment]
ohk

**Comment by OutdatedGuy** [comment]
Closing as completed in #74, #75 and #76
