### ISSUE TITLE
Create Rating tab in user profile

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/Trip-Management-System#72]
@OutdatedGuy create Rating tab for user profile same as wallet tab
input required
1. Get Trip (Button): To show all trip eligible for Rating
2. form data : trip ID, rating out of 5, description if any

API Route: I will provide later

**Comment by malivinayak** [comment]
@OutdatedGuy I have look this

**Comment by OutdatedGuy** [comment]
@malivinayak

API Routes used:
1. Get trips eligible for rating: `/api/trip/rateable`
2. Rate trip: `/api/trip/rate`
