### ISSUE TITLE
Create frontend for driver dashboard 

### ISSUE THREAD

**Issue by OutdatedGuy** [malivinayak/Trip-Management-System#78]
## Get Available Trip
API Route: `/api/trip/available`
> **Get Available Trips** is button which will show available trips as per driver's category
- [x] token

## Accept trip
API route: `/api/trip/accept`
- [x] tripID
- [x] token

## History

- [x] Get history button that will send user token to backend and display trip records(`/api/trip/history/driver`)
- [x] Delete all button that will send token to backend (`/api/trip/delete/driver`)

## Wallet

- [x] Get current balance button that will send user token to backend (`/api/cbs/get-balance/driver`)
- [x] withdraw money form that will send amount and user token to backend (`/api/cbs/withdraw-money`)

**Comment by malivinayak** [comment]
@OutdatedGuy check the requirements

**Comment by OutdatedGuy** [comment]
Make api for accepting trip to be `/api/trip/accept`
