### ISSUE TITLE
change user name and driver name to userid and driverid in trip query for admin

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/Trip-Management-System#93]
issue: admin may fill any name either first name lastn ame middle name or full name, it is quite challenging to develop such query in less time.
solution: So just replace it with userid and driverid
NOTE: Don't change variable name of passing data. keep it same as userNname and driverName

![image](https://user-images.githubusercontent.com/66154908/204183354-e17b0b02-2e47-420d-b0ab-ffa2f2424e67.png)

**Comment by malivinayak** [comment]
- [ ] Add status field near ac in admin trip query

![image](https://user-images.githubusercontent.com/66154908/204184231-bd64d04b-7506-4fce-a6f9-efeb3b6cdc45.png)

can you add it? if yes then convert it into issue

**Comment by OutdatedGuy** [comment]
@malivinayak, those fields are meant for user and driver IDs only. Not their names.
