### ISSUE TITLE
create more fields for start and end time in admin trip query

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/Trip-Management-System#94]
at startTrip time their must be two fields
- [x] D1 - from this date time to
- [x] D2 - that date time

same at endTrip time their must be two fields
- [x] D1 - from this date time to
- [x] D2 - that date time

issue - no one knows exact start and end time with seconds so admin can't apply filter on it

I am taking 4 fields from req.body
- [x] startDateTime1
- [x] startDateTime2
- [x] endDateTime1
- [x] endDateTime2

**Comment by OutdatedGuy** [comment]
@malivinayak, cannot do till tomorrow. Busy with other work.

**Comment by malivinayak** [comment]
@OutdatedGuy No issue 
do on day after tomorrow
